const timezones = new Map([
    ["America/Anchorage", "Alaska Time Zone (AKST/AKDT)"],
    ["America/Puerto_Rico", "Atlantic Standart Time (AST)"],
    ["America/Halifax", "Atlantic Time Zone (AST/ADT)"],
    ["Australia/North", "Australian Central Standart Time (ACST)"],
    ["Australia/South", "Australian Central Time Zone (ACST/ACDT)"],
    ["Australia/Brisbane", "Australian Eastern Standart Time (AEST)"],
    ["Australia/Canberra", "Australian Eastern Time Zone (AEST/AEDT)"],
    ["Australia/West", "Australian Western Standart Time (AWST)"],
    ["America/Chicago", "Central Standart Time (CST)"],
    ["Africa/Khartoum", "Central Africa Time (CAT)"],
    ["Africa/Tunis", "Central European Summer Time (CEST)"],
    ["CET", "Central European Time (CET/CEST)"],
    ["Asia/Shanghai", "China Standart Time (CST)"],
    ["Pacific/Guam", "Chammoro Time Zone (ChST)"],
    ["America/Costa_Rica", "Central Standart Time (CST)"],
    ["Asia/Makassar", "Central Indonesian Time (WITA)"],
    ["America/Chicago", "Central Time Zone (CST/CDT)"],
    ["Africa/Dar_es_Salaam", "East Africa Time (EAT)"],
    ["Europe/Kaliningrad", "Eastern European Time (EET)"],
    ["Europe/Tallinn", "Eastern European Standart Time (EET/EEST)"],
    ["America/Jamaica", "Eastern Standart Time (EST)"],
    ["America/Detroit", "Eastern Time Zone (EST/EDT)"],
    ["Asia/Jayapura", "Eastern Indonesian Time (WIT)"],
    ["Etc/GMT", "Greenwich Mean Time (GMT)"],
    ["GB", "Greenwich Mean T./British Summer T. (GMT/BST)"],
    ["Eire", "Greenwich Mean T./Irish Standart T. (GMT/IST)"],
    ["Asia/Hong_Kong", "Hong Kong Time (HKT)"],
    ["Pacific/Honolulu", "Hawaii-Aleutian Standart Time (HST)"],
    ["America/Adak", "Hawaii-Aleutian Time Zone (HST/HDT)"],
    ["Asia/Kolkata", "Indian Standart Time (IST)"],
    ["Israel", "Israel Time Zone (IST/IDT)"],
    ["Asia/Tokyo", "Japan Standart Time (JST)"],
    ["Asia/Seoul", "Korean Standart Time (KST)"],
    ["America/Denver", "Mountain Time Zone (MST/MDT)"],
    ["America/Phoenix", "Mountain Standart Time (MST)"],
    ["Europe/Moscow", "Moscow Time (MSK)"],
    ["Canada/Newfoundland", "Newfoundland Time Zone (NST/NDT)"],
    ["Pacific/Auckland", "New Zealand Standart Time (NZST/NZDT)"],
    ["Asia/Karachi", "Pakistan Standart Time (PKT)"],
    ["America/Los_Angeles", "Pacific Time Zone (PST/PDT)"],
    ["Asia/Manila", "Philiphine Standart Time (PST)"],
    ["Pacific/Pago_Pago", "Samoa Standart Time (SST)"],
    ["Africa/Johannesburg", "South Africa Standart Time (SAST)"],
    ["Etc/UTC", "Universal Time Zone (UTC)"],
    ["Africa/Lagos", "West Africa Time (WAT)"],
    ["WET", "Western European Time (WET/WEST)"],
    ["Asia/Jakarta", "Western Indonesian Time (WIB)"]
]);
const zones = new Map([
    ["Etc/GMT+12", "GMT -12"],
    ["Etc/GMT+11", "GMT -11"],
    ["Etc/GMT+10", "GMT -10"],
    ["Etc/GMT+9", "GMT -9"],
    ["Etc/GMT+8", "GMT -8"],
    ["Etc/GMT+7", "GMT -7"],
    ["Etc/GMT+6", "GMT -6"],
    ["Etc/GMT+5", "GMT -5"],
    ["Etc/GMT+4", "GMT -4"],
    ["Etc/GMT+3", "GMT -3"],
    ["Etc/GMT+2", "GMT -2"],
    ["Etc/GMT+1", "GMT -1"],
    ["Etc/GMT-0", "GMT +0"],
    ["Etc/GMT-1", "GMT +1"],
    ["Etc/GMT-2", "GMT +2"],
    ["Etc/GMT-3", "GMT +3"],
    ["Etc/GMT-4", "GMT +4"],
    ["Etc/GMT-5", "GMT +5"],
    ["Etc/GMT-6", "GMT +6"],
    ["Etc/GMT-7", "GMT +7"],
    ["Etc/GMT-8", "GMT +8"],
    ["Etc/GMT-9", "GMT +9"],
    ["Etc/GMT-10", "GMT +10"],
    ["Etc/GMT-11", "GMT +11"],
    ["Etc/GMT-12", "GMT +12"],
    ["Etc/GMT-13", "GMT +13"],
    ["Etc/GMT-14", "GMT +14"],
]);
const countrys = new Map([
    ["Pacific/Niue", "Niue"],
    ["Pacific/Midway", "Midway"],
    ["Pacific/Samoa", "Samoa"],
    ["Pacific/Rarotonga", "Wyspy Cooka"],
    ["Pacific/Tahiti", "Polinezja Francuska (WT)"],
    ["America/Adak", "Alaska (ZA)"],
    ["Pacific/Honolulu", "Hawaje"],
    ["Pacific/Marquesas", "Polinezja Francuska (Markizy)"],
    ["Pacific/Gambier", "Polinezja Francuska (WG)"],
    ["America/Anchorage", "Alaska"],
    ["Pacific/Pitcairn", "Pitcairn"],
    ["America/Los_Angeles", "Los Angeles - CA (US)"],
    ["America/Tijuana", "Tijuana - BCA (MX)"],
    ["America/Vancouver", "Vancouver - BC (CA)"],
    ["America/Denver", "Denver - CO (US)"],
    ["America/Edmonton", "Edmonton - AB (CA)"],
    ["America/Whitehorse", "Whitehorse - YT (CA)"],
    ["America/Phoenix", "Phoenix - AZ (US)"],
    ["America/Mazatlan", "Mazatlan - SN (MX)"],
    ["Pacific/Easter", "Wyspa Wielkanocna"],
    ["Pacific/Galapagos", "Wyspy Galapagos"],
    ["America/Chicago", "Chicago - IL (US)"],
    ["America/Matamoros", "Matamoros - TM (MX)"],
    ["America/Winnipeg", "Winnipeg - MB (CA)"],
    ["America/Chihuahua", "Chihuahua - CH (MX)"],
    ["America/Regina", "Regina - SK (CA)"],
    ["America/Belize", "Belize"],
    ["America/Costa_Rica", "Kostaryka"],
    ["America/El_Salvador", "Salwador"],
    ["America/Guatemala", "Gwatemala"],
    ["America/Managua", "Nikaragua"],
    ["America/Tegucigalpa", "Honduras"],
    ["America/Bogota", "Kolumbia"],
    ["America/Eirunepe", "Eirunepe (Brazylia)"],
    ["America/Guayaquil", "Ekwador"],
    ["America/Lima", "Peru"],
    ["America/Rio_Branco", "Rio Branco (Brazylia)"],
    ["America/Havana", "Kuba"],
    ["America/Detroit", "Detroit - MI (US)"],
    ["America/Iqaluit", "Iqaluit - NU (CA)"],
    ["America/Grand_Turk", "Turks i Caicos"],
    ["America/New_York", "Nowy Jork - NY (US)"],
    ["America/Port-au-Prince", "Haiti"],
    ["America/Toronto", "Toronto - ON (CA)"],
    ["America/Toronto", "Bahamy"],
    ["America/Cancun", "Cancun - YK (MX)"],
    ["America/Jamaica", "Jamajka"],
    ["America/Panama", "Panama"],
    ["America/Panama", "Wyspy Kajmana"],
    ["America/Santiago", "Chile"],
    ["America/Campo_Grande", "Campo Grande (Brazylia)"],
    ["America/Caracas", "Wenezuela"],
    ["America/Guyana", "Gujana"],
    ["America/La_Paz", "Boliwia"],
    ["America/Halifax", "Halifax - NS (CA)"],
    ["America/Thule", "Thule (Grenlandia)"],
    ["Atlantic/Bermuda", "Bermudy"],
    ["America/Anguilla", "Anguilla"],
    ["America/Antigua", "Antigua"],
    ["America/Aruba", "Aruba"],
    ["America/Barbados", "Barbados"],
    ["America/Curacao", "Curaçao"],
    ["America/Dominica", "Dominika"],
    ["America/Grenada", "Grenada"],
    ["America/Guadeloupe", "Gwadelupa"],
    ["America/Kralendijk", "Holandia Karaibska"],
    ["America/Lower_Princes", "Sint Maarten"],
    ["America/Marigot", "Saint Martin"],
    ["America/Martinique", "Martynika"],
    ["America/Montserrat", "Montserrat"],
    ["America/Puerto_Rico", "Portoryko"],
    ["America/Santo_Domingo", "Dominikana"],
    ["America/St_Barthelemy", "Wspólnota Saint-Barthélemy"],
    ["America/St_Kitts", "Saint Kitts i Nevis"],
    ["America/St_Lucia", "Saint Lucia"],
    ["America/St_Thomas", "Wyspy Dziewicze"],
    ["America/St_Vincent", "Saint Vincent i Grenadyny"],
    ["America/Tortola", "Brytyjskie Wyspy Dziewicze"],
    ["America/St_Johns", "St. John's - NL (CA)"],
    ["America/Miquelon", "Wspólnota Saint Pierre i Miquelon"],
    ["America/Araguaina", "Araguiana (Brazylia)"],
    ["America/Buenos_Aires", "Buenos Aires (Argentyna)"],
    ["America/Asuncion", "Paragwaj"],
    ["America/Cayenne", "Gujana Francuska"],
    ["America/Punta_Arenas", "Punta Arenas (Chile)"],
    ["America/Montevideo", "Urugwaj"],
    ["America/Sao_Paulo", "Sao Paulo (Brazylia)"],
    ["Antarctica/Rothera", "Rothera (Antarktyda)"],
    ["Atlantic/Stanley", "Falklandy"],
    ["America/Nuuk", "Nuuk (Grenlandia)"],
    ["America/Noronha", "Noronha"],
    ["Atlantic/South_Georgia", "Georgia Płd. i Sandwich Płd."],
    ["Atlantic/Cape_Verde", "Republika Zielonego Przylądka"],
    ["Atlantic/Azores", "Azory (Portugalia)"],
    ["Antarctica/Troll", "Troll (Antarktyda)"],
    ["Europe/Isle_of_Man", "Wyspa Man"],
    ["Europe/Guernsey", "Guernsey"],
    ["Europe/Belfast", "Belfast"],
    ["Europe/Jersey", "Jersey"],
    ["Europe/London", "Wielka Brytania"],
    ["Africa/Abidjan", "Wybrzeże Kości Słoniowej"],
    ["Africa/Accra", "Ghana"],
    ["Africa/Bamako", "Mali"],
    ["Africa/Banjul", "Gambia"],
    ["Africa/Bissau", "Gwinea Bissau"],
    ["Africa/Conakry", "Gwinea"],
    ["Africa/Dakar", "Senegal"],
    ["Africa/Freetown", "Sierra Leone"],
    ["Africa/Lome", "Togo"],
    ["Africa/Monrovia", "Liberia"],
    ["Africa/Nouakchott", "Mauretania"],
    ["Africa/Ouagadougou", "Burkina Faso"],
    ["Africa/Sao_Tome", "Wyspy Świętego Tomasza i Książęca"],
    ["America/Danmarkshavn", "Danmarkshavn (Grenlandia)"],
    ["Atlantic/Reykjavik", "Islandia"],
    ["Atlantic/St_Helena", "Święta Helena"],
    ["Europe/Dublin", "Irlandia"],
    ["Atlantic/Canary", "Wyspy Kanaryjskie"],
    ["Atlantic/Faroe", "Wyspy Owcze"],
    ["Atlantic/Madeira", "Madera"],
    ["Europe/Lisbon", "Portugalia"],
    ["Arctic/Longyearbyen", "Svalbard"],
    ["Europe/Andorra", "Andorra"],
    ["Europe/Madrid", "Hiszpania"],
    ["Europe/Amsterdam", "Holandia"],
    ["Europe/Belgrade", "Serbia"],
    ["Europe/Bratislava", "Słowacja"],
    ["Europe/Brussels", "Belgia"],
    ["Europe/Copenhagen", "Dania"],
    ["Europe/Budapest", "Węgry"],
    ["Europe/Gibraltar", "Gibraltar"],
    ["Europe/Ljubljana", "Słowenia"],
    ["Europe/Luxembourg", "Luksemburg"],
    ["Europe/Malta", "Malta"],
    ["Europe/Monaco", "Monako"],
    ["Europe/Oslo", "Norwegia"],
    ["Europe/Paris", "Francja"],
    ["Europe/Podgorica", "Czarnogóra"],
    ["Europe/Prague", "Czechy"],
    ["Europe/Rome", "Włochy"],
    ["Europe/San_Marino", "San Marino"],
    ["Europe/Sarajevo", "Bośnia i Hercegowina"],
    ["Europe/Skopje", "Macedonia Północna"],
    ["Europe/Stockholm", "Szwecja"],
    ["Europe/Tirane", "Albania"],
    ["Europe/Vaduz", "Liechtenstein"],
    ["Europe/Vatican", "Watykan"],
    ["Europe/Vienna", "Austria"],
    ["Europe/Warsaw", "Polska"],
    ["Europe/Zurich", "Szwajcaria"],
    ["Africa/Algiers", "Algieria"],
    ["Africa/Lagos", "Nigeria"],
    ["Africa/Libreville", "Gabon"],
    ["Africa/Luanda", "Angola"],
    ["Africa/Malabo", "Gwinea Równikowa"],
    ["Africa/Ndjamena", "Czad"],
    ["Africa/Niamey", "Niger"],
    ["Africa/Porto-Novo", "Benin"],
    ["Africa/Blantyre", "Malawi"],
    ["Africa/Bujumbura", "Burundi"],
    ["Africa/Gaborone", "Botswana"],
    ["Africa/Harare", "Zimbabwe"],
    ["Africa/Juba", "Sudan Południowy"],
    ["Africa/Khartoum", "Sudan"],
    ["Africa/Kigali", "Rwanda"],
    ["Africa/Lubumbashi", "Demokratyczna Republika Konga"],
    ["Africa/Lusaka", "Zambia"],
    ["Africa/Maputo", "Mozambik"],
    ["Africa/Windhoek", "Namibia"],
    ["Africa/Cairo", "Egipt"],
    ["Asia/Beirut", "Liban"],
    ["Asia/Nicosia", "Cypr"],
    ["Asia/Gaza", "Palestyna"],
    ["Europe/Athens", "Grecja"],
    ["Europe/Bucharest", "Rumunia"],
    ["Europe/Chisinau", "Mołdawia"],
    ["Europe/Helsinki", "Finladnia"],
    ["Europe/Mariehamn", "Wyspy Alandzkie (Finlandia)"],
    ["Europe/Kyiv", "Ukraina"],
    ["Europe/Riga", "Łotwa"],
    ["Europe/Sofia", "Bułgaria"],
    ["Europe/Tallinn", "Estonia"],
    ["Europe/Vilnus", "Litwa"],
    ["Europe/Kaliningrad", "Królewiec (Rosja)"],
    ["Africa/Tripoli", "Libia"],
    ["Asia/Jerusalem", "Izrael"],
    ["Africa/Maseru", "Lesotho"],
    ["Africa/Mbabane", "Eswatini"],
    ["Africa/Johannesburg", "Republika Południowej Afryki"],
    ["Antarctica/Syowa", "Syowa (Antarktyda)"],
    ["Asia/Aden", "Jemen"],
    ["Pacific/Chatham", "Wyspy Chatham (GMT +12:45/13:45)"]
]);
const select = document.querySelector("#timezone");

const optionc = document.createElement("option");
optionc.textContent = 'Kraje';
optionc.disabled = true;
select.appendChild(optionc);

countrys.forEach((text, value) => {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = text;
    select.appendChild(option);
});

const optiont = document.createElement("option");
optiont.textContent = 'Czasy';
optiont.disabled = true;
select.appendChild(optiont);

timezones.forEach((text, value) => {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = text;

    if (value === "Etc/UTC") option.selected = true;

    select.appendChild(option);
});
const optionz = document.createElement("option");
optionz.textContent = 'Strefy czasowe';
optionz.disabled = true;
select.appendChild(optionz);
zones.forEach((text, value) => {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = text;
    select.appendChild(option);
});