const timezones = new Map([
    ["America/Anchorage", "Alaska Time Zone (AKST/AKDT)"],
    ["America/Puerto_Rico", "Atlantic Standard Time (AST)"],
    ["America/Halifax", "Atlantic Time Zone (AST/ADT)"],
    ["Australia/North", "Australian Central Standard Time (ACST)"],
    ["Australia/South", "Australian Central Time Zone (ACST/ACDT)"],
    ["Australia/Brisbane", "Australian Eastern Standard Time (AEST)"],
    ["Australia/Canberra", "Australian Eastern Time Zone (AEST/AEDT)"],
    ["Australia/West", "Australian Western Standard Time (AWST)"],
    ["America/Mexico_City", "Central Standard Time (CST)"],
    ["Africa/Khartoum", "Central Africa Time (CAT)"],
    ["Africa/Tunis", "Central European Time (CET)"],
    ["CET", "Central European Time (CET/CEST)"],
    ["Asia/Shanghai", "China Standard Time (CST)"],
    ["Pacific/Guam", "Chamorro Time Zone"],
    ["America/Costa_Rica", "Central Standard Time (CST)"],
    ["Asia/Makassar", "Central Indonesian Time (WITA)"],
    ["America/Chicago", "Central Time Zone (CST/CDT)"],
    ["Africa/Dar_es_Salaam", "East Africa Time (EAT)"],
    ["Europe/Kaliningrad", "Eastern European Time (EET)"],
    ["Europe/Tallinn", "Eastern European Standard Time (EET/EEST)"],
    ["America/Jamaica", "Eastern Standard Time (EST)"],
    ["America/Detroit", "Eastern Time Zone (EST/EDT)"],
    ["Asia/Jayapura", "Eastern Indonesian Time (WIT)"],
    ["Etc/GMT", "Greenwich Mean Time (GMT)"],
    ["Europe/London", "Greenwich Mean T./British Summer T. (GMT/BST)"],
    ["Europe/Dublin", "Greenwich Mean T./Irish Standard T. (GMT/IST)"],
    ["Asia/Hong_Kong", "Hong Kong Time (HKT)"],
    ["Pacific/Honolulu", "Hawaii-Aleutian Standard Time (HST)"],
    ["America/Adak", "Hawaii-Aleutian Time Zone (HST/HDT)"],
    ["Asia/Kolkata", "Indian Standard Time (IST)"],
    ["Asia/Jerusalem", "Israel Time Zone (IST/IDT)"],
    ["Asia/Tokyo", "Japan Standard Time (JST)"],
    ["Asia/Seoul", "Korean Standard Time (KST)"],
    ["America/Denver", "Mountain Time Zone (MST/MDT)"],
    ["America/Phoenix", "Mountain Standard Time (MST)"],
    ["Europe/Moscow", "Moscow Time (MSK)"],
    ["Canada/Newfoundland", "Newfoundland Time Zone (NST/NDT)"],
    ["Pacific/Auckland", "New Zealand Standard Time (NZST/NZDT)"],
    ["Asia/Karachi", "Pakistan Standard Time (PKT)"],
    ["America/Los_Angeles", "Pacific Time Zone (PST/PDT)"],
    ["Asia/Manila", "Philippine Standard Time"],
    ["Pacific/Pago_Pago", "Samoa Standard Time (SST)"],
    ["Africa/Johannesburg", "South Africa Standard Time (SAST)"],
    ["Etc/UTC", "Universal Time Zone (UTC)"],
    ["Africa/Lagos", "West Africa Time (WAT)"],
    ["WET", "Western European Time (WET/WEST)"],
    ["Asia/Jakarta", "Western Indonesian Time (WIB)"]
]);
const zones = new Map([
    ["Etc/GMT+12", "GMT -12"],
    ["Etc/GMT+11", "GMT -11"],
    ["Etc/GMT+10", "GMT -10"],
    ["Etc/GMT+9", "GMT -9"],
    ["Etc/GMT+8", "GMT -8"],
    ["Etc/GMT+7", "GMT -7"],
    ["Etc/GMT+6", "GMT -6"],
    ["Etc/GMT+5", "GMT -5"],
    ["Etc/GMT+4", "GMT -4"],
    ["Etc/GMT+3", "GMT -3"],
    ["Etc/GMT+2", "GMT -2"],
    ["Etc/GMT+1", "GMT -1"],
    ["Etc/GMT-0", "GMT +0"],
    ["Etc/GMT-1", "GMT +1"],
    ["Etc/GMT-2", "GMT +2"],
    ["Etc/GMT-3", "GMT +3"],
    ["Etc/GMT-4", "GMT +4"],
    ["Etc/GMT-5", "GMT +5"],
    ["Etc/GMT-6", "GMT +6"],
    ["Etc/GMT-7", "GMT +7"],
    ["Etc/GMT-8", "GMT +8"],
    ["Etc/GMT-9", "GMT +9"],
    ["Etc/GMT-10", "GMT +10"],
    ["Etc/GMT-11", "GMT +11"],
    ["Etc/GMT-12", "GMT +12"],
    ["Etc/GMT-13", "GMT +13"],
    ["Etc/GMT-14", "GMT +14"],
]);
const countries = new Map([
    ["Asia/Kabul", "Afganistan"],
    ["Europe/Tirane", "Albania"],
    ["Africa/Algiers", "Algieria"],
    ["Europe/Andorra", "Andorra"],
    ["Africa/Luanda", "Angola"],
    ["America/Anguilla", "Anguilla"],
    ["Antarctica/South_Pole", "Antarktyda - Biegun Południowy"],
    ["Antarctica/Casey", "Antarktyda - Casey"],
    ["Antarctica/Davis", "Antarktyda - Davis"],
    ["Antarctica/DumontDUrville", "Antarktyda - Dumont-d'Urville"],
    ["Antarctica/McMurdo", "Antarktyda - McMurdo"],
    ["Antarctica/Rothera", "Antarktyda - Rothera"],
    ["Antarctica/Syowa", "Antarktyda - Syowa"],
    ["Antarctica/Troll", "Antarktyda - Troll"],
    ["Antarctica/Vostok", "Antarktyda - Wostok"],
    ["Antarctica/Macquarie", "Antarktyda - Wyspa Macquarie"],
    ["America/Antigua", "Antigua"],
    ["Asia/Riyadh", "Arabia Saudyjska"],
    ["Asia/Yerevan", "Armenia"],
    ["America/Buenos_Aires", "Argentyna"],
    ["America/Aruba", "Aruba"],
    ["Australia/Adelaide", "Australia - Adelajda"],
    ["Australia/Brisbane", "Australia - Brisbane"],
    ["Australia/Broken_Hill", "Australia - Broken Hill"],
    ["Australia/Darwin", "Australia - Darwin"],
    ["Australia/Eucla", "Australia - Eucla"],
    ["Australia/Hobart", "Australia - Hobart"],
    ["Australia/Lindeman", "Australia - Lindeman"],
    ["Australia/Melbourne", "Australia - Melbourne"],
    ["Australia/Perth", "Australia - Perth"],
    ["Australia/Sydney", "Australia - Sydney"],
    ["Australia/Lord_Howe", "Australia - Wyspa Lord Howe"],
    ["Europe/Vienna", "Austria"],
    ["Asia/Baku", "Azerbejdżan"],
    ["America/Nassau", "Bahamy"],
    ["Asia/Bahrain", "Bahrain"],
    ["Asia/Dhaka", "Bangladesz"],
    ["America/Barbados", "Barbados"],
    ["Europe/Brussels", "Belgia"],
    ["America/Belize", "Belize"],
    ["Africa/Porto-Novo", "Benin"],
    ["Atlantic/Bermuda", "Bermudy"],
    ["Europe/Minsk", "Białoruś"],
    ["Asia/Yangon", "Birma"],
    ["America/La_Paz", "Boliwia"],
    ["Europe/Sarajevo", "Bośnia i Hercegowina"],
    ["Africa/Gaborone", "Botswana"],
    ["America/Brasilia", "Brazylia - Brasilia"],
    ["America/Araguaina", "Brazylia - Araguaina"],
    ["America/Campo_Grande", "Brazylia - Campo Grande"],
    ["America/Eirunepe", "Brazylia - Eirunepe"],
    ["America/Rio_Branco", "Brazylia - Rio Branco"],
    ["America/Sao_Paulo", "Brazylia - Sao Paulo"],
    ["Asia/Brunei", "Brunei Darussalam"],
    ["Indian/Chagos", "Brytyjskie Terytorium Oceanu Indyjskiego"],
    ["America/Tortola", "Brytyjskie Wyspy Dziewicze"],
    ["Europe/Sofia", "Bułgaria"],
    ["Africa/Ouagadougou", "Burkina Faso"],
    ["Africa/Bujumbura", "Burundi"],
    ["Asia/Thimphu", "Butan"],
    ["America/Santiago", "Chile - Santiago"],
    ["America/Punta_Arenas", "Chile - Punta Arenas"],
    ["Asia/Shanghai", "Chiny - Pekin"],
    ["Asia/Hong_Kong", "Chiny - Hong Kong"],
    ["Asia/Macau", "Chiny - Makau"],
    ["Asia/Urumqi", "Chiny - Urumczi"],
    ["America/Curacao", "Curaçao"],
    ["Asia/Nicosia", "Cypr"],
    ["Africa/Ndjamena", "Czad"],
    ["Europe/Podgorica", "Czarnogóra"],
    ["Europe/Prague", "Czechy"],
    ["Europe/Copenhagen", "Dania"],
    ["Pacific/Wake", "Dalekie Wyspy Mniejsze Stanów Zjednoczonych"],
    ["Africa/Lubumbashi", "Demokratyczna Republika Konga"],
    ["America/Dominica", "Dominika"],
    ["America/Santo_Domingo", "Dominikana"],
    ["Africa/Cairo", "Egipt"],
    ["America/Guayaquil", "Ekwador"],
    ["Europe/Tallinn", "Estonia"],
    ["Africa/Mbabane", "Eswatini"],
    ["Atlantic/Stanley", "Falklandy"],
    ["Pacific/Fiji", "Fidżi"],
    ["Asia/Manila", "Filipiny"],
    ["Europe/Helsinki", "Finlandia"],
    ["Europe/Paris", "Francja"],
    ["Africa/Libreville", "Gabon"],
    ["Africa/Banjul", "Gambia"],
    ["Atlantic/South_Georgia", "Georgia Południowa i Sandwich Południowy"],
    ["Africa/Accra", "Ghana"],
    ["Europe/Gibraltar", "Gibraltar"],
    ["Europe/Athens", "Grecja"],
    ["America/Grenada", "Grenada"],
    ["America/Nuuk", "Grenlandia - Nuuk"],
    ["America/Danmarkshavn", "Grenlandia - Danmarkshavn"],
    ["America/Thule", "Grenlandia - Thule"],
    ["Asia/Tbilisi", "Gruzja"],
    ["Pacific/Guam", "Guam"],
    ["Europe/Guernsey", "Guernsey"],
    ["America/Guyana", "Gujana"],
    ["America/Cayenne", "Gujana Francuska"],
    ["America/Guadeloupe", "Gwadelupa"],
    ["America/Guatemala", "Gwatemala"],
    ["Africa/Conakry", "Gwinea"],
    ["Africa/Bissau", "Gwinea Bissau"],
    ["Africa/Malabo", "Gwinea Równikowa"],
    ["America/Port-au-Prince", "Haiti"],
    ["Pacific/Honolulu", "Hawaje"],
    ["Europe/Madrid", "Hiszpania"],
    ["Europe/Amsterdam", "Holandia"],
    ["America/Kralendijk", "Holandia Karaibska"],
    ["America/Tegucigalpa", "Honduras"],
    ["Asia/Kolkata", "Indie"],
    ["Asia/Baghdad", "Irak"],
    ["Asia/Tehran", "Iran"],
    ["Europe/Dublin", "Irlandia"],
    ["Asia/Jakarta", "Indonezja - Dżakarta"],
    ["Asia/Jayapura", "Indonezja - Dżajapura"],
    ["Asia/Makassar", "Indonezja - Makassar"],
    ["Asia/Pontianak", "Indonezja - Pontianak"],
    ["Atlantic/Reykjavik", "Islandia"],
    ["Asia/Jerusalem", "Izrael"],
    ["America/Jamaica", "Jamajka"],
    ["Asia/Tokyo", "Japonia"],
    ["Asia/Aden", "Jemen"],
    ["Europe/Jersey", "Jersey"],
    ["Asia/Amman", "Jordania"],
    ["Asia/Phnom_Penh", "Kambodża"],
    ["Asia/Qatar", "Katar"],
    ["America/Edmonton", "Kanada - Edmonton"],
    ["America/Iqaluit", "Kanada - Iqaluit"],
    ["America/Halifax", "Kanada - Halifax"],
    ["America/Regina", "Kanada - Regina"],
    ["America/St_Johns", "Kanada - St. John's"],
    ["America/Toronto", "Kanada - Toronto"],
    ["America/Vancouver", "Kanada - Vancouver"],
    ["America/Whitehorse", "Kanada - Whitehorse"],
    ["America/Winnipeg", "Kanada - Winnipeg "],
    ["Asia/Almaty", "Kazachstan"],
    ["Asia/Bishkek", "Kirgistan"],
    ["Pacific/Enderbury", "Kiribati - Enderbury"],
    ["Pacific/Kanton", "Kiribati - Kanton"],
    ["Pacific/Kiritimati", "Kiribati - Kiritimati"],
    ["Pacific/Tarawa", "Kiribati - Tarawa"],
    ["America/Bogota", "Kolumbia"],
    ["Indian/Comoro", "Komory"],
    ["Asia/Seoul", "Korea Południowa"],
    ["Asia/Pyongyang", "Korea Północna"],
    ["Pacific/Chuuk", "Mikronezja - Chuuk"],
    ["Pacific/Kosrae", "Mikronezja - Kosrae"],
    ["Pacific/Pohnpei", "Mikronezja - Pohnpei"],
    ["America/Costa_Rica", "Kostaryka"],
    ["America/Havana", "Kuba"],
    ["Asia/Kuwait", "Kuwejt"],
    ["Asia/Vientiane", "Laos"],
    ["Africa/Maseru", "Lesotho"],
    ["Asia/Beirut", "Liban"],
    ["Africa/Monrovia", "Liberia"],
    ["Africa/Tripoli", "Libia"],
    ["Europe/Vaduz", "Liechtenstein"],
    ["Europe/Vilnius", "Litwa"],
    ["Europe/Luxembourg", "Luksemburg"],
    ["Europe/Riga", "Łotwa"],
    ["Europe/Skopje", "Macedonia Północna"],
    ["Indian/Antananarivo", "Madagaskar"],
    ["Atlantic/Madeira", "Madera"],
    ["Indian/Mayotte", "Majotta"],
    ["Africa/Blantyre", "Malawi"],
    ["Indian/Maldives", "Malediwy"],
    ["Asia/Kuala_Lumpur", "Malezja"],
    ["Africa/Bamako", "Mali"],
    ["Europe/Malta", "Malta"],
    ["Pacific/Saipan", "Mariany Północne"],
    ["America/Martinique", "Martynika"],
    ["Africa/Nouakchott", "Mauretania"],
    ["Indian/Mauritius", "Mauritius"],
    ["America/Cancun", "Meksyk - Cancun"],
    ["America/Chihuahua", "Meksyk - Chihuahua"],
    ["America/Mexico_City", "Meksyk - Meksyk (Miasto)"],
    ["America/Matamoros", "Meksyk - Matamoros"],
    ["America/Mazatlan", "Meksyk - Mazatlan"],
    ["America/Tijuana", "Meksyk - Tijuana"],
    ["Pacific/Midway", "Midway"],
    ["Europe/Chisinau", "Mołdawia"],
    ["Europe/Monaco", "Monako"],
    ["Asia/Ulaanbaatar", "Mongolia"],
    ["America/Montserrat", "Montserrat"],
    ["Africa/Maputo", "Mozambik"],
    ["Africa/Windhoek", "Namibia"],
    ["Pacific/Nauru", "Nauru"],
    ["Asia/Kathmandu", "Nepal"],
    ["Africa/Niamey", "Niger"],
    ["Africa/Lagos", "Nigeria"],
    ["America/Managua", "Nikaragua"],
    ["Pacific/Niue", "Niue"],
    ["America/Noronha", "Noronha"],
    ["Europe/Oslo", "Norwegia"],
    ["Pacific/Noumea", "Nowa Kaledonia"],
    ["Pacific/Auckland", "Nowa Zelandia"],
    ["Asia/Muscat", "Oman"],
    ["Asia/Karachi", "Pakistan"],
    ["Pacific/Palau", "Palau"],
    ["Asia/Gaza", "Palestyna"],
    ["America/Panama", "Panama"],
    ["America/Asuncion", "Paragwaj"],
    ["America/Lima", "Peru"],
    ["Pacific/Pitcairn", "Pitcairn"],
    ["Pacific/Marquesas", "Polinezja Francuska - Markizy"],
    ["Pacific/Papeete", "Polinezja Francuska - Papeete"],
    ["Pacific/Gambier", "Polinezja Francuska - Wyspy Gambiera"],
    ["Pacific/Tahiti", "Polinezja Francuska - Wyspy Towarzystwa"],
    ["Europe/Warsaw", "Polska"],
    ["Pacific/Port_Moresby", "Papua-Nowa Gwinea - Port Moresby"],
    ["Pacific/Bougainville", "Papua-Nowa Gwinea - Bougainville"],
    ["America/Puerto_Rico", "Portoryko"],
    ["Europe/Lisbon", "Portugalia - Lizbona"],
    ["Atlantic/Azores", "Portugalia - Azory"],
    ["Africa/Johannesburg", "Republika Południowej Afryki"],
    ["Atlantic/Cape_Verde", "Republika Zielonego Przylądka"],
    ["Indian/Reunion", "Reunion"],
    ["Asia/Anadyr", "Rosja - Anadyr"],
    ["Europe/Astrakhan", "Rosja - Astrachań"],
    ["Asia/Barnaul", "Rosja - Barnauł"],
    ["Asia/Chita", "Rosja - Czyta"],
    ["Asia/Irkutsk", "Rosja - Irkuck"],
    ["Asia/Yakutsk", "Rosja - Jakuck"],
    ["Asia/Yekaterinburg", "Rosja - Jekaterynburg"],
    ["Asia/Kamchatka", "Rosja - Kamczatka"],
    ["Europe/Kaliningrad", "Rosja - Królewiec"],
    ["Asia/Krasnoyarsk", "Rosja - Krasnojarsk"],
    ["Europe/Kirov", "Rosja - Kirow"],
    ["Asia/Magadan", "Rosja - Magadan"],
    ["Europe/Moscow", "Rosja - Moskwa"],
    ["Asia/Novokuznetsk", "Rosja - Nowokuznieck"],
    ["Asia/Novosibirsk", "Rosja - Nowosybirsk"],
    ["Asia/Omsk", "Rosja - Omsk"],
    ["Asia/Sakhalin", "Rosja - Sachalin"],
    ["Europe/Samara", "Rosja - Samara"],
    ["Europe/Saratov", "Rosja - Saratów"],
    ["Asia/Srednekolymsk", "Rosja - Sriedniekołymsk"],
    ["Asia/Tomsk", "Rosja - Tomsk"],
    ["Europe/Ulyanovsk", "Rosja - Uljanowsk"],
    ["Asia/Ust-Nera", "Rosja - Ust'-Niera"],
    ["Asia/Vladivostok", "Rosja - Władywostok"],
    ["Europe/Volgograd", "Rosja - Wołgograd"],
    ["Europe/Bucharest", "Rumunia"],
    ["Africa/Kigali", "Rwanda"],
    ["America/St_Kitts", "Saint Kitts i Nevis"],
    ["America/St_Lucia", "Saint Lucia"],
    ["America/Marigot", "Saint Martin"],
    ["America/St_Vincent", "Saint Vincent i Grenadyny"],
    ["America/El_Salvador", "Salwador"],
    ["Pacific/Apia", "Samoa"],
    ["Pacific/Pago_Pago", "Samoa Amerykańskie"],
    ["Europe/San_Marino", "San Marino"],
    ["Africa/Dakar", "Senegal"],
    ["Europe/Belgrade", "Serbia"],
    ["Indian/Mahe", "Seszele"],
    ["Africa/Freetown", "Sierra Leone"],
    ["Asia/Singapore", "Singapur"],
    ["America/Lower_Princes", "Sint Maarten"],
    ["Europe/Bratislava", "Słowacja"],
    ["Europe/Ljubljana", "Słowenia"],
    ["Asia/Colombo", "Sri Lanka"],
    ["America/Anchorage", "Stany Zjednoczone - Anchorage"],
    ["America/Adak", "Stany Zjednoczone - Zachodnie Aleuty"],
    ["America/Chicago", "Stany Zjednoczone - Chicago"],
    ["America/Denver", "Stany Zjednoczone - Denver"],
    ["America/Detroit", "Stany Zjednoczone - Detroit"],
    ["America/Los_Angeles", "Stany Zjednoczone - Los Angeles"],
    ["America/New_York", "Stany Zjednoczone - Nowy Jork"],
    ["America/Phoenix", "Stany Zjednoczone - Phoenix"],
    ["Africa/Khartoum", "Sudan"],
    ["Africa/Juba", "Sudan Południowy"],
    ["Arctic/Longyearbyen", "Svalbard"],
    ["Europe/Simferopol", "Krym"],
    ["Asia/Damascus", "Syria"],
    ["Europe/Zurich", "Szwajcaria"],
    ["Europe/Stockholm", "Szwecja"],
    ["Atlantic/St_Helena", "Święta Helena"],
    ["Asia/Dushanbe", "Tadżykistan"],
    ["Asia/Bangkok", "Tajlandia"],
    ["Asia/Taipei", "Tajwan"],
    ["Indian/Kerguelen", "Francuskie Terytoria Południowe i Arktyczne"],
    ["Asia/Dili", "Timor Wschodni"],
    ["Africa/Lome", "Togo"],
    ["Pacific/Fakaofo", "Tokelau"],
    ["Pacific/Tongatapu", "Tonga"],
    ["Asia/Istanbul", "Turcja"],
    ["Asia/Ashgabat", "Turkmenistan"],
    ["America/Grand_Turk", "Turks i Caicos"],
    ["Pacific/Funafuti", "Tuwalu"],
    ["Europe/Kyiv", "Ukraina"],
    ["America/Montevideo", "Urugwaj"],
    ["Asia/Tashkent", "Uzbekistan"],
    ["Pacific/Wallis", "Wallis i Futuna"],
    ["Pacific/Efate", "Wanuatu"],
    ["Europe/Vatican", "Watykan"],
    ["America/Caracas", "Wenezuela"],
    ["Europe/Budapest", "Węgry"],
    ["Europe/London", "Wielka Brytania"],
    ["Asia/Ho_Chi_Minh", "Wietnam"],
    ["Europe/Rome", "Włochy"],
    ["America/Miquelon", "Wspólnota Terytorialna Saint Pierre i Miquelon"],
    ["America/St_Barthelemy", "Wspólnota Saint-Barthélemy"],
    ["Africa/Abidjan", "Wybrzeże Kości Słoniowej"],
    ["Indian/Christmas", "Wyspa Bożego Narodzenia"],
    ["Pacific/Norfolk", "Wyspa Norfolk"],
    ["Europe/Isle_of_Man", "Wyspa Man"],
    ["Pacific/Easter", "Wyspa Wielkanocna"],
    ["Europe/Mariehamn", "Wyspy Alandzkie"],
    ["Pacific/Chatham", "Wyspy Chatham"],
    ["Pacific/Rarotonga", "Wyspy Cooka"],
    ["America/St_Thomas", "Wyspy Dziewicze"],
    ["Pacific/Galapagos", "Wyspy Galapagos"],
    ["America/Cayman", "Wyspy Kajmana"],
    ["Atlantic/Canary", "Wyspy Kanaryjskie"],
    ["Indian/Cocos", "Wyspy Kokosowe"],
    ["Pacific/Kwajalein", "Wyspy Marshalla"],
    ["Atlantic/Faroe", "Wyspy Owcze"],
    ["Pacific/Guadalcanal", "Wyspy Salomona"],
    ["Africa/Sao_Tome", "Wyspy Świętego Tomasza i Książęca"],
    ["Africa/Lusaka", "Zambia"],
    ["Africa/Harare", "Zimbabwe"],
    ["Asia/Dubai", "Zjednoczone Emiraty Arabskie"]
]);